### ISSUE TITLE
save_pretrained() 에 NotImplemented Error 발생

### ISSUE THREAD

**Issue by seunggyu-42maru** [SKT-AI/KoBART#14]
안녕하세요. 먼저 좋은 모델을 공개해주셔서 감사합니다.

모델의 토크나이저를 사용하는 도중 에러가 발생하여 이슈를 남깁니다.

## 환경
- Python 3.6.9
- Transformers 4.3.3
- torch 1.7.1+cu110
- CUDA Version 11.2
- KoBART 0.4 ( `git+https://github.com/SKT-AI/KoBART#egg=kobart` 로 pip install 진행)
- 데이터셋은 자체적으로 구축한 한국어 데이터셋 사용

## 오류가 발생한 코드
(일부 불필요한 내용은 생략하였습니다)
```python
import kobart
from transformers import AutoTokenizer
if not os.path.exists("./kobart_tokenizer"):
    os.makedirs("./kobart_tokenizer")
dummy_tokenizer = kobart.get_kobart_tokenizer() 
dummy_tokenizer.save_pretrained("./kobart_tokenizer/") # 이곳에서 에러 발생
tokenizer = AutoTokenizer.from_pretrained("./kobart_tokenizer")
```

## 오류 내용
```
Traceback (most recent call last):
  File "misc.py", line 23, in <module>
    dummy_tokenizer.save_pretrained("./kobart_tokenizer/")
  File ".../venv/lib/python3.6/site-packages/transformers/tokenization_utils_base.py", line 1992, in save_pretrained
    filename_prefix=filename_prefix,
  File ".../venv/lib/python3.6/site-packages/transformers/tokenization_utils_fast.py", line 535, in _save_pretrained
    vocab_files = self.save_vocabulary(save_directory, filename_prefix=filename_prefix)
  File ".../venv/lib/python3.6/site-packages/transformers/tokenization_utils_base.py", line 2044, in save_vocabulary
    raise NotImplementedError
NotImplementedError
```

## 추가 설명
이 오류는 다음과 같은 코드에서 발생한 pickle 에러를 해결하려던 도중 발견하였습니다.

```python
tokenizer = kobart.get_kobart_tokenizer()
def preprocess(sample):
    global tokenizer
    return tokenizer(sample)

# 생략

def main():
    # 생략
    dataset = dataset.map(preprocess, batched=True)
```

를 진행할 시, map 이 있는 라인에서 pickling Error가 발생합니다. (에러 내용이 너무 길어 일부 생략하고 마지막 부분만 기입합니다)
```
File ".../venv/lib/python3.6/pickle.py", line 927, in save_global
    (obj, module_name, name))
_pickle.PicklingError: Can't pickle <class 'transformers.tokenization_utils_fast.PreTrainedTokenizerFast'>: it's not the same object as transformers.tokenization_utils_fast.PreTrainedTokenizerFast
```
이 문제를 회피하는 방법 중에 하나로, `preprocess(sample)` 안에서 `get_kobart_tokenizer()`를 하는 방법이 있었습니다만 매번 토크나이저를 불러오게 되어 굉장히 느리고 비효율적이라고 판단되었습니다.
huggingface에서 제공하는 다른 tokenizer의 경우, 위와 같이 하나의 토크나이저를 미리 선언해둔 후 map에서 사용하여도 아무런 문제가 발생하지 않았습니다.
이를 해결하려고 tokenizer를 일단 불러온 후, `save_pretrained()` 를 하고 다시 `AutoTokenizer.from_pretrained()` 로 가져와서 실행해보려던 중 `NotImplementedError`가 발생하였습니다.
맥락이 다를 수는 있지만 아무래도 `not the same object as ...PreTrainedTokenizerFast` 부분이, 토크나이저의 일부가 구현되지 않아 생기는 오류일 수 있다는 생각에 이슈에 같이 기입하였습니다.

**Comment by haven-jeon** [comment]
같은 모델이 https://huggingface.co/gogamza/kobart-base-v1 에도 올라가 있는데 HF 라이브러리로 확인 부탁드립니다.

**Comment by seunggyu-42maru** [comment]
위와 동일한 환경에서 Python 버전만 `3.7.10` 으로 바꾸고 진행하였습니다.

`model = AutoModel.from_pretrained("gogamza/kobart-base-v1")` 은 정상적으로 작동하였으나

```
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    tokenizer = AutoTokenizer.from_pretrained("gogamza/kobart-base-v1")
  File ".../venv/lib/python3.7/site-packages/transformers/models/auto/tokenization_auto.py", line 373, in from_pretrained
    tokenizer_class = tokenizer_class_from_name(tokenizer_class_candidate)
  File ".../venv/lib/python3.7/site-packages/transformers/models/auto/tokenization_auto.py", line 273, in tokenizer_class_from_name
    if c.__name__ == class_name:
AttributeError: 'NoneType' object has no attribute '__name__'
```
는 정상적으로 작동하지 않는 것 같습니다.

**Comment by haven-jeon** [comment]
```
tokenizer = PreTrainedTokenizerFast.from_pretrained('gogamza/kobart-base-v1')
```

위와 같이 호출하시기 바랍니다. 

그리고 'save_pretrained' 하려는 이유가 무엇인지 궁금합니다. from_pretrained를 실행하면 HF 모듈은 캐싱을 하기 때문에 다시 다운로드를 하지 않는데 말이죠.. 

참고로 아직 이슈가 오픈되어 있기는 한데 관련된 링크 공유 드립니다. 

https://github.com/huggingface/transformers/issues/8125

**Comment by seunggyu-42maru** [comment]
안녕하세요. 
말씀해주신 방법으로 HF에서 다운로드 받는 형태로 사용하여도 
1. 여전히 save_vocabulary 에서 NotImplementedError 가 발생하며,
2. '추가 설명' 에서 말씀드린 것과 같이 map() 에서 토크나이저를 미리 선언해둔 후 진행하려고 하면 pickling error가 발생합니다.

--------------

save_pretrained에서 오류가 발생한 것을 알게 된 것은 첫 글에서 말씀드린 것처럼 큰 생각 없이 한번 로컬에 다시 저장했다가 가져오면 오류가 해결될까 하는 의문에서 시도하면서 알게 되었습니다.

다만 이 이슈를 적고 나서 스스로 문제를 해결해보려고 하는 과정에서 save_pretrained가 Trainer에서도 사용된다는 사실을 발견하였습니다.

save_vocabulary에서 NotImplementedError를 발견하고 이를 직접 해결해보고자 PreTrainedTokenizerFast를 상속받은 새 클래스를 만들고 여기에 해당 내용을 구현하여 사용하였습니다.

```Python
from kobart.utils import tokenizer, download

import os
from pathlib import Path
from transformers import PreTrainedTokenizerFast
from transformers.models.bart.modeling_bart import BartForConditionalGeneration, shift_tokens_right
from typing import  Optional, Tuple
from zipfile import ZipFile
import shutil
import json


# Fixing the kobart for usability

class PTTFwithSaveVocab(PreTrainedTokenizerFast):
    def __init__ (self, *args, **kwargs):
        super().__init__(*args, **kwargs)
    
    def save_vocabulary(self, save_directory: str, filename_prefix: Optional[str] = None) -> Tuple[str]:
        """
        See https://huggingface.co/transformers/_modules/transformers/tokenization_utils_base.html#save_vocabulary for docstring of original save_vocabulary.
        """
        file_path = os.path.expanduser(save_directory)
        Path(file_path).mkdir(parents=True, exist_ok=True)
        prefix = filename_prefix if filename_prefix else ""
        full_path_with_filename = file_path + prefix + 'vocab.json' # 오타 난 부분
        with open(full_path_with_filename, 'w', encoding='utf-8') as vocab_file:
            json.dump(self.get_vocab(), vocab_file, ensure_ascii=False)
        
        return (full_path_with_filename,)


def get_kobart_tokenizer(cachedir='~/kobart/'):
    """Get KoGPT2 Tokenizer file path after downloading
    """
    global tokenizer
    model_info = tokenizer
    file_path, is_cached = download(model_info['url'],
                                    model_info['fname'],
                                    model_info['chksum'],
                                    cachedir=cachedir)
    cachedir_full = os.path.expanduser(cachedir)
    if not os.path.exists(os.path.join(cachedir_full, 'emji_tokenizer')) or not is_cached:
        if not is_cached:
            shutil.rmtree(os.path.join(cachedir_full, 'emji_tokenizer'), ignore_errors=True)
        zipf = ZipFile(os.path.expanduser(file_path))
        zipf.extractall(path=cachedir_full)
    tok_path = os.path.join(cachedir_full, 'emji_tokenizer/model.json')
    tokenizer_obj = PTTFwithSaveVocab(tokenizer_file=tok_path,
                                      bos_token='<s>', eos_token='</s>', unk_token='<unk>', sep_token='</s>',
                                      pad_token='<pad>', mask_token='<mask>')
    return tokenizer_obj
```

위의 코드에서 제가 `full_path_with_filename = file_path + prefix + 'vocab.json'` 에서 vocab 앞에 `/`를 깜빡한 오타를 낸 것을 볼 수 있는데, 이 상태에서 Trainer를 통해 checkpoint를 생성하니 `./output/checkpoint100vocab.json` 이 생성되는 것을 확인하였습니다. 깜빡했던 `/`를 넣어 `full_path_with_filename = file_path + prefix + '/vocab.json'` 로 수정하니 정상적으로 `./output/checkpoint-100/vocab.json` 처럼 하위 폴더 안에 다른 모델 체크포인트 파일들과 함께 저장되었습니다.

따라서 이 문제는 Trainer를 이용하여 체크포인트를 정상적으로 저장하기 위해서라도 해결되어야 하지 않나 생각합니다.

감사합니다.

**Comment by haven-jeon** [comment]
이 부분은 Huggingface 측에 이슈를 제안하는게 맞아 보입니다.  어떠신가요?

**Comment by seunggyu-42maru** [comment]
음... 그렇다고 하기엔 huggingface에서 제공하는 다른 tokenizer들은 거의 대부분 정상작동하고, KoBART에서 제공하는 토크나이저에서만 위에서 말씀드린 에러들이 발생하고 있습니다.

예를 들어, huggingface에서 제공하는 bert-base-uncased를 사용하면

```Python
Python 3.7.10 (default, May  3 2021, 02:48:31)
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from transformers import BertTokenizer
>>> tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")
Downloading: 100%|███████████████████████████████████| 232k/232k [00:00<00:00, 317kB/s]
>>> tokenizer.tokenize("Testing bert based cased tokenizer from huggingface.")
['testing', 'bert', 'based', 'case', '##d', 'token', '##izer', 'from', 'hugging', '##face', '.']
>>> tokenizer.save_pretrained('./bert-based-uncased/')
('./bert-based-uncased/tokenizer_config.json', './bert-based-uncased/special_tokens_map.json', './bert-based-uncased/vocab.txt', './bert-based-uncased/added_tokens.json')
>>>
```
save_pretrained 오류도 발생하지 않고,

```Python
>>> from datasets import load_dataset
>>> dataset = load_dataset("imdb", split="test")
Reusing dataset imdb (.../.cache/huggingface/datasets/imdb/plain_text/1.0.0/e3c66f1788a67a89c7058d97ff62b6c30531e05b549de56d3ab91891f0561f9a)
>>> def preprocess(sample):
...     return tokenizer(sample["text"])
...
>>> tokenized_dataset = dataset.map(preprocess)
  0%|                                                        | 0/25000 [00:00<?, ?ex/s]Token indices sequence length is longer than the specified maximum sequence length for this model (1352 > 512). Running this sequence through the model will result in indexing errors
100%|███████████████████████████████████████████| 25000/25000 [01:46<00:00, 234.78ex/s]
>>>
```
tokenizer를 사전에 선언해둔 후 preprocess 함수를 이용한 dataset.map 을 사용해도 문제없이 작동하는 것을 확인할 수 있었습니다.

**Comment by haven-jeon** [comment]
KoBART 토크나이저는 HF에서 만든 `tokenizers`로 빌드 되었습니다. HF transformers와  tokenizers가 그렇게 호환이 좋은 상황은 아닌데, 아마도 그런 이유 때문으로 보입니다.  현재 `save_pretrained` 함수는 KoBART 토크나이저 클래스를 정의해서 구현해야 될거로 보입니다. 아쉽게도 여러 상황으로 볼때 관련 구현은 빠른 시일내로는 어려울 것 같아 보입니다. 아무래도 vocab을 확장하고 튜닝 후 나중에 쓰려고 하시는듯한 상황이신거 같습니다만, 해당 구현에 대해서 필요하시다면 구현 후 PR 주시는것도 어떨까 하는 생각을 해봅니다.

**Comment by haven-jeon** [comment]
피드백이 없어 일단 해당 이슈는 클로즈 합니다.  필요시 재 오픈하겠습니다.
